replicaCount: 1

image:
  repository: docker.io/mittalmah01/three_tier_backend
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  MONGO_DB_URL: mongodb://mongodb-svc:27017/todo?directConnection=true
  MONGO_SECRET: mongo-sec

